**2021.7.28 (202107280)**
- Fixed issues.
- Major refactoring
- Updated framework and documentation.

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -1,204 +1,282 @@
 #!/system/bin/sh
 # $id Installer/Upgrader
-# Copyright (c) 2019, VR25 (xda-developers.com)
+# Copyright 2019-2021, VR25
 # License: GPLv3+
+#
+# devs: triple hashtags (###) mark non-generic code
 
-set +x
+
+# override the official Magisk module installer
+SKIPUNZIP=1
+
+
 echo
 id=djs
-umask 077
+domain=vr25
+umask 0077
+data_dir=/data/adb/$domain/${id}-data
+
 
 # log
-mkdir -p /data/adb/${id}-data/logs
-exec 2>/data/adb/${id}-data/logs/install.log
+[ -z "${LINENO-}" ] || export PS4='$LINENO: '
+mkdir -p $data_dir/logs
+exec 2>$data_dir/logs/install.log
 set -x
 
-trap 'e=$?; echo; exit $e' EXIT
+
+exxit() {
+  local e=$?
+  set +eu
+  rm -rf /dev/.$domain.${id}-install /data/adb/modules_update/$id
+  (abort) > /dev/null
+  echo
+  exit $e
+} 2>/dev/null
+
+trap exxit EXIT
+
 
 # set up busybox
-if [ -d /sbin/.magisk/busybox ]; then
-  [[ $PATH == /sbin/.magisk/busybox* ]] || PATH=/sbin/.magisk/busybox:$PATH
-elif [ -d /sbin/.core/busybox ]; then
-  [[ $PATH == /sbin/.core/busybox* ]] || PATH=/sbin/.core/busybox:$PATH
-else
-  [[ $PATH == /dev/.busybox* ]] || PATH=/dev/.busybox:$PATH
-  if ! mkdir -m 700 /dev/.busybox 2>/dev/null; then
-    if [ -x /data/adb/magisk/busybox ]; then
-      /data/adb/magisk/busybox --install -s /dev/.busybox
-    elif which busybox > /dev/null; then
-      busybox --install -s /dev/.busybox
-    else
-      echo "(!) Install busybox binary first"
-      exit 3
-    fi
+#BB#
+[ -x /dev/.vr25/busybox/ls ] || {
+  mkdir -p /dev/.vr25/busybox
+  chmod 0700 /dev/.vr25/busybox
+  if [ -f /data/adb/vr25/bin/busybox ]; then
+    [ -x /data/adb/vr25/bin/busybox ] || chmod -R 0700 /data/adb/vr25/bin
+    /data/adb/vr25/bin/busybox --install -s /dev/.vr25/busybox
+  elif [ -f /data/adb/magisk/busybox ]; then
+    [ -x /data/adb/magisk/busybox ] || chmod 0700 /data/adb/magisk/busybox
+    /data/adb/magisk/busybox --install -s /dev/.vr25/busybox
+  elif which busybox > /dev/null; then
+    eval "$(which busybox) --install -s /dev/.vr25/busybox"
+  else
+    echo "(!) Install busybox or simply place it in /data/adb/vr25/bin/"
+    exit 3
   fi
-fi
+}
+case $PATH in
+  /data/adb/vr25/bin:*) :;;
+  *) export PATH=/data/adb/vr25/bin:/dev/.vr25/busybox:$PATH;;
+esac
+#/BB#
+
 
 # root check
-if [ $(id -u) -ne 0 ]; then
+[ $(id -u) -ne 0 ] && {
   echo "(!) $0 must run as root (su)"
   exit 4
-fi
+}
 
-print() { sed -n "s|^$1=||p" ${2:-$srcDir/module.prop}; }
+
+get_prop() { sed -n "s|^$1=||p" ${2:-$srcDir/module.prop}; }
 
 set_perms() {
   local owner=${2:-0} perms=0600 target=$(readlink -f $1)
   if echo $target | grep -q '.*\.sh$' || [ -d $target ]; then perms=0700; fi
   chmod $perms $target
   chown $owner:$owner $target
-  restorecon $target > /dev/null 2>&1 || :
+  chcon u:object_r:system_file:s0 $target
 }
 
 set_perms_recursive() {
-  local owner=${2:-0} target=""
+  local owner=${2-0} target=""
   find $1 2>/dev/null | while read target; do set_perms $target $owner; done
 }
 
-set -euo pipefail
+set -eu
+
 
 # set source code directory
 [ -f $PWD/${0##*/} ] && srcDir=$PWD || srcDir=${0%/*}
+srcDir=${srcDir/#"${0##*/}"/"."}
 
-# unzip flashable zip if source code is unavailable
-if [ ! -f $srcDir/module.prop ]; then
-  srcDir=/dev/.tmp
+
+# extract flashable zip if source code is unavailable
+[ -f $srcDir/module.prop ] || {
+  srcDir=/dev/.$domain.${id}-install
   rm -rf $srcDir 2>/dev/null || :
   mkdir $srcDir
-  unzip -o ${ZIP:-${3:-}} -d $srcDir/ >&2
+  unzip "${3:-${ZIPFILE}}" -d $srcDir/ >&2
+}
+
+
+name=$(get_prop name)
+author=$(get_prop author)
+version=$(get_prop version)
+magiskModDir=/data/adb/modules
+versionCode=$(get_prop versionCode)
+accaFiles=/data/data/mattecarra.accapp/files ###
+: ${installDir:=$accaFiles} ###
+config=$data_dir/config.txt
+
+
+[ -d $magiskModDir ] && magisk=true || magisk=false
+ls -d ${accaFiles%/*}* > /dev/null 2>&1 && acca=true || acca=false ###
+
+
+# ensure AccA's files/ exists - to prevent unwanted downgrades ###
+if $acca && [ ! -d $accaFiles ]; then
+  mkdir -p $accaFiles
+  chmod 0777 ${accaFiles%/*} $accaFiles
 fi
 
-name=$(print name)
-author=$(print author)
-version=$(print version)
-versionCode=$(print versionCode)
-installDir=${installDir0:-/data/data/mattecarra.accapp/files}
-config=/data/media/0/$id/${id}.conf
 
-# migrate/restore config
-[ -f $config ] || mv ${config%/*}/config.txt $config 2>/dev/null || :
-if [ -d ${config%/*} ] && [ ! -d /data/adb/${id}-data ]; then
-  mv $config ${config%/*}/config.txt 2>/dev/null || :
-  (cd /data/media/0; mv ${config%/*} ${id}-data
-  tar -cf - ${id}-data | tar -xf - -C /data/adb)
-  rm -rf ${id}-data
-fi
-config=/data/adb/${id}-data/config.txt
-[ -f $config ] || cp /data/media/0/.${id}-config-backup.txt $config 2>/dev/null || :
-
-configVer=$(print versionCode $config 2>/dev/null || :)
-
-# check/set parent installation directory
-[ -d $installDir ] || installDir=/sbin/.magisk/modules
-[ -d $installDir ] || installDir=/sbin/.core/img
-[ -d $installDir ] || installDir=/data/adb
-[ -d $installDir ] || { echo "(!) /data/adb/ not found\n"; exit 1; }
+# check/change parent installation directory
+! $magisk || installDir=$magiskModDir
+[ $installDir != /data/adb/vr25 ] || mkdir -p $installDir
+[ -d $installDir ] || {
+  installDir=/data/adb/vr25
+  mkdir -p $installDir
+}
 
 
-cat << EOF
-$name $version
-Copyright (c) 2019, $author
-License: GPLv3+
+###
+echo "$name $version ($versionCode)
+Copyright 2019-2021, $author
+GPLv3+
 
-(i) Installing to $installDir/$id/...
-EOF
+(i) Installing in $installDir/$id/..."
 
 
-(pkill -9 -f "/$id (-|--)|/${id}d.sh" ) || :
-
-# install
-rm -rf $(readlink -f /sbin/.$id/$id) $installDir/$id 2>/dev/null || :
+/system/bin/sh $srcDir/$id/uninstall.sh install
 cp -R $srcDir/$id/ $installDir/
-installDir=$installDir/$id
-[ ${installDir0:-x} == x ] && installDir0=/data/data/mattecarra.accapp/files/$id || installDir0=$installDir0/$id
+installDir=$(readlink -f $installDir/$id)
 cp $srcDir/module.prop $installDir/
+cp -f $srcDir/README.md $data_dir/
 
-mkdir -p ${config%/*}/info
-cp -f $srcDir/*.md ${config%/*}/info
 
-case $installDir in
-  /data/adb/$id|$installDir0)
-    mv $installDir/service.sh $installDir/${id}-init.sh;;
-  *)
-    ln $installDir/service.sh $installDir/post-fs-data.sh;;
-esac
+###
+! $magisk || {
+  # symlink executables
+  mkdir -p $installDir/system/bin
 
-# patch/upgrade config
-if [ -f $config ]; then
-  if [ ${configVer:-0} -lt 201906290 ] \
-      || [ ${configVer:-0} -gt $(print versionCode $installDir/default-config.txt) ]
-    then
-      rm $config
-  else
-    if [ $configVer -lt 201908180 ]; then
-      echo "// This is a comment line" >> $config
-      sed -i -e '/^versionCode=/s/=.*/=201908180/' -e 's|^#|//|' $config
-    fi
-  fi
+  ln -sf $installDir/djs-config.sh $installDir/system/bin/djsc
+  ln -sf $installDir/djs-config.sh $installDir/system/bin/djs-config
+
+  ln -sf $installDir/service.sh $installDir/system/bin/djsd
+  ln -sf $installDir/service.sh $installDir/system/bin/djs-daemon
+
+  ln -sf $installDir/djs-status.sh $installDir/system/bin/djs,
+  ln -sf $installDir/djs-status.sh $installDir/system/bin/djs-status
+
+  ln -sf $installDir/djs-stop.sh $installDir/system/bin/djs.
+  ln -sf $installDir/djs-stop.sh $installDir/system/bin/djs-stop
+
+  ln -sf $installDir/djs-version.sh $installDir/system/bin/djsv
+  ln -sf $installDir/djs-version.sh $installDir/system/bin/djs-version
+}
+
+
+###
+if $acca; then
+
+  ! $magisk || {
+
+    ln -fs $installDir $accaFiles/
+
+    # AccA post-uninstall cleanup script
+    mkdir -p /data/adb/service.d || {
+      rm /data/adb/service.d
+      mkdir /data/adb/service.d
+    }
+    echo "#!/system/bin/sh
+      # AccA post-uninstall cleanup script
+
+      until test -d /sdcard/Android \\
+        && test .\$(getprop sys.boot_completed) = .1
+      do
+        sleep 60
+      done
+
+      sleep 60
+
+      [ -e $accaFiles/$id ] || rm -rf \$0 /data/adb/$domain/$id /data/adb/modules/$id 2>/dev/null
+
+      exit 0" | sed 's/^      //' > /data/adb/service.d/${id}-cleanup.sh
+    chmod 0700 /data/adb/service.d/${id}-cleanup.sh
+  }
 fi
 
-cp -f $srcDir/bin/${id}-uninstaller.zip /data/media/0/
+
+[ $installDir = /data/adb/$domain/$id ] || {
+  mkdir -p /data/adb/vr25
+  ln -s $installDir /data/adb/$domain/
+}
+
+
+# install binaries
+cp -f $srcDir/bin/${id}-uninstaller.zip $data_dir/
+
+
+# Termux, fix shebang
+[[ $installDir != *com.termux* ]] && termux=false || {
+  termux=true
+  for f in $installDir/*.sh; do
+    ! grep -q '^#\!/.*/sh' $f \
+      || sed -i 's|^#!/.*/sh|#!/data/data/com.termux/files/usr/bin/bash|' $f
+  done
+}
+
 
 # set perms
-set_perms_recursive ${config%/*}
-chmod 0666 /data/media/0/${id}-uninstaller.zip
 case $installDir in
-  /data/*/files/$id)
-    pkg=${installDir%/files/$id}
+  /data/*/files/*$id)
+    pkg=${installDir%/files/*$id}
     pkg=${pkg##/data*/}
-    owner=$(grep $pkg /data/system/packages.list | awk '{print $2}')
-    set_perms_recursive ${installDir%/*} $owner
+    owner=$(grep $pkg /data/system/packages.list | cut -d ' ' -f 2)
+    set_perms_recursive $installDir $owner
+
+    # Termux:Boot
+    ! $termux || {
+      mkdir -p ${installDir%/*}/.termux/boot
+      ln -sf $installDir/service.sh ${installDir%/*}/.termux/boot/${id}-init.sh
+      chown -R $(stat -c %u:%g /data/data/com.termux) ${installDir%/*}/.termux
+      chmod -R 0755 ${installDir%/*}/.termux
+      /system/bin/restorecon -R ${installDir%/*}/.termux > /dev/null 2>&1
+    }
   ;;
   *)
     set_perms_recursive $installDir
   ;;
 esac
 
-set +euo pipefail
+
+set +eu
 
 
-cat << EOF
-- Done
-
-  LATEST CHANGES
-
-EOF
+echo "- Done
 
 
-# print changelog
-tail -n +$(grep -n \($versionCode\) ${config%/*}/info/README.md | cut -d: -f1) \
-  ${config%/*}/info/README.md | sed 's/^/    /'
+"
+# print links and changelog
+sed -En "\|^## LINKS|,\$p" $srcDir/README.md \
+  | grep -v '^---' | sed 's/^## //'
 
 
-cat << EOF
-
-  LINKS
-    - Donate: paypal.me/vr25xda/
-    - Facebook page: facebook.com/VR25-at-xda-developers-258150974794782/
-    - Git repository: github.com/VR-25/$id/
-    - Telegram channel: t.me/vr25_xda/
-    - Telegram profile: t.me/vr25xda/
-
-(i) Rebooting is unnecessary.
-- $id can be used right now.
-- $id daemon started.
-EOF
+###
+echo "
 
 
-[ $installDir == /data/adb ] && echo -e "\n(i) Use init.d or an app to run $installDir/${id}-init.sh on boot to initialize ${id}."
+(i) Rebooting is unnecessary
+- $id commands may require the "/dev/.$domain/$id/" prefix (e.g., /dev/.$domain/$id/${id}c) until system is rebooted.
+- Daemon started."
 
-echo
-trap - EXIT
+
+case $installDir in
+  /data/adb/*) echo "
+(i) Non-Magisk users can enable $id auto-start by running /data/adb/$domain/$id/service.sh, a copy of, or a link to it - with init.d or an app that emulates it."
+  ;;
+esac
+
+
+#legacy
+if $acca; then
+  ln -s $installDir/service.sh $installDir/${id}-init.sh
+  ln -s $installDir $accaFiles/
+fi 2>/dev/null
+
 
 # initialize $id
-if grep -q /storage/emulated /proc/mounts; then
-  if [ -f $installDir/service.sh ]; then
-    $installDir/service.sh --override
-  else
-    $installDir/${id}-init.sh --override
-  fi
-fi
+/data/adb/$domain/$id/service.sh
 
-e=$?
-[ $e -eq 0 ] || { echo; exit $e; }
 exit 0
